name: prod-front

on:
  push:
    branches: [ "update/CICD" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy-front:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/proceos
            git pull origin master
            cd react-app
            wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            nvm use 12
            npm install
            npm run build